import type { Metadata } from "next";
import { IBM_Plex_Sans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { MobileSideBar, SideBar } from "../components/shared/sidebar";
const inter = IBM_Plex_Sans({ subsets: ["latin"] ,
weight:['400' ,'500','600',"700"],
variable:'--font-ibm-plex'
});

export const metadata: Metadata = {
  title: "Next Level",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   <main className="root">
    <SideBar/>
    <MobileSideBar/>
    <div className=" root-container">
        <div className="wrapper">
            {children}
        </div>
    </div>
   </main>
  );
}
